services:
  dsp2-env:
    build: .
    container_name: dsp2_dev
    # Mapeia a pasta atual (host) para /app (contêiner).
    # O sufixo :z foi removido para manter compatibilidade entre Linux e WSL 2.
    volumes:
      - .:/app
    stdin_open: true
    tty: true
